apiVersion: v1
kind: Pod
metadata:
  name: hello-booking
  namespace: random-namespace   # Specify the namespace
  labels:
    app: truebook
    service: hello-booking
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - truebook
              - key: service
                operator: In
                values:
                  - hello-booking
          topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    location: dev
  schedulerName: default-scheduler
  containers:
    - name: hello-booking
      image: swapnil333/hello-booking
