apiVersion: v1
kind: Service
metadata:
  name: hello-booking-service
  namespace: custom-namespace   # Specify the namespace
spec:
  selector:
    app: truebook
    service: hello-booking
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: NodePort
